### ISSUE TITLE
FakeCORS 

### ISSUE THREAD

**Issue by puria** [dyne/interfacer-gateway#11]
There are attempts from the GUI to communicate with gateway1 without success seems for CORS problems???
Or something else hided, by CORS problems ;p

Please double check and make sure if the reason is something else to, expose correct error messages. Maybe related to #2

**Comment by puria** [comment]
![Screenshot_20230207_091219](https://user-images.githubusercontent.com/10379/217188530-850ea475-3b9d-46c6-ab64-e7b798fbddc4.png)

**Comment by protodeniz** [comment]
It is up an running now.
