### ISSUE TITLE
MQTT implementation inside proxy

### ISSUE THREAD

**Issue by puria** [dyne/interfacer-gateway#13]

**Comment by albertolerda** [comment]
I imagine proxy will have to "convert" between MQTT and REST API. When interfacer-gui want to send a message to Fabaccess he sends a HTTP request to the proxy and he will use MQTT. Moreover, if there is a response from MQTT, interfacer-gui will have to use polling through HTTP.

**Comment by albertolerda** [comment]
Temporary using https://github.com/interfacerproject/zenflows-fabaccess

**Comment by protodeniz** [comment]
Closing this as Alberto confirmed it is unnecessary now.
