### ISSUE TITLE
Add license header to all source files

### ISSUE THREAD

**Issue by protodeniz** [dyne/interfacer-gateway#3]
This is required due to legal and boring stuff.

**Comment by protodeniz** [comment]
Will be taken care of by when I'm done with my changes.

**Comment by puria** [comment]
Please consider to use reuse tool for that (while ago wrote something about that https://dyne.org/handbook-dev/#/howto/licensing, for people not used to it) and consider adding also a check with https://github.com/fsfe/reuse-action ;)
