### ISSUE TITLE
Instead of creating a buffer and writing that to the net/http.ResponseWriter, write the stuff directly

### ISSUE THREAD

**Issue by protodeniz** [dyne/interfacer-gateway#4]
Since `net/http.ResponseWriter` implements the `io.Writer` interface, we can convert the "write into a `buf`, copy that `buf` into `net/http.ResponseWriter`" (which is used throughout the source code) into something like `fmt.Fprintf(w, "string")`, which is more idiomatic and better performance-wise, since it skips and intermediate variable which the runtime allocates memory for.

**Comment by albertolerda** [comment]
Can you point to the line of the code, I am coping the body directly https://github.com/interfacerproject/interfacer-gateway/blob/1a58bc43b69752a826af1b6c93ce3cceac15d68d/main.go#L153

Do you mean in the error case https://github.com/interfacerproject/interfacer-gateway/blob/1a58bc43b69752a826af1b6c93ce3cceac15d68d/main.go#L117-L119 ? Yes we could

**Comment by protodeniz** [comment]
When merged, will be taken care of by https://github.com/interfacerproject/interfacer-proxy/pull/9.

**Comment by protodeniz** [comment]
https://github.com/interfacerproject/interfacer-proxy/pull/9 is merged.
